name: cheri-zephyr-combined Build

on:
  push:
    branches:
      - main
    paths:
      - zephyr/**
      - .github/workflows/cheri-zephyr-combined-build.yml
  workflow_dispatch: # Allows manual triggering of this workflow

jobs:
  build-and-push:
    runs-on: the-capable-hub-aws-ci
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    env:
      REPO_DIR: ${{ github.workspace }}/volatile/repo
      REPO_NAME: ${{ github.event.repository.name }}
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
      GHCR_REGISTRY: ghcr.io
      GHCR_ORG_NAME: the-capable-hub
      DOCKER_REGISTRY: docker.io
      DOCKER_ORG_NAME: capablehub
      # Default to false
      SHOULD_PUSH: false

    steps:
      - name: Checkout repository ${{ env.REPO_NAME }}
        uses: actions/checkout@v4
        with:
          path: ${{ env.REPO_DIR }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} 
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Container Registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_IO_NAME }} 
          password: ${{ secrets.DOCKER_IO_TOKEN }} 

      - name: Determine push status
        # IF main branch AND push event, enable push
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          echo "This is a push to ${{ env.BRANCH_NAME }}, so we will publish the containers."
          echo "SHOULD_PUSH=true" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5 
        with:
          context: ${{ env.REPO_DIR }}
          file: ${{ env.REPO_DIR }}/zephyr/Dockerfile-combined
          push: ${{ env.SHOULD_PUSH }}
          tags: |
            ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_ORG_NAME }}/cheri-zephyr-combined:v0.2.0
            ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_ORG_NAME }}/cheri-zephyr-combined:latest
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_ORG_NAME }}/cheri-zephyr-combined:v0.2.0
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_ORG_NAME }}/cheri-zephyr-combined:latest
          platforms: linux/amd64