name: Multi-arch-workflow

on:
  push:
    branches:
      - "wbeasley/ci-testing"
  workflow_dispatch:

jobs:
   Hello_World:
      runs-on: the-capable-hub-aws-ci

      steps:
         - name: Hello_World
           run: |
              echo "Hello!"

         - name: Check arch
           run: |
              uname -a

   Hello_World_ARM:
      runs-on: the-capable-hub-aws-ci-arm64

      steps:
         - name: Hello_World
           run: |
              echo "Hello!"

         - name: Check arch
           run: |
              uname -a

   Hello_World_AMD64:
      runs-on: the-capable-hub-aws-ci-amd64

      steps:
         - name: Hello_World
           run: |
              echo "Hello!"

         - name: Check arch
           run: |
              uname -a
